---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lyl69.
--- DateTime: 2025/5/14 23:57
---
--具体业务
local key = KEYS[1]
--区分观看、点赞和收藏
local cntKey = ARGV[1]

local delta = tonumber(ARGV[2])
local exists=redis.call("EXISTS",key)
if exists==1 then
    redis.call("HINCRBY",key,cntKey,delta)
    return 1
else
    return 0
end