// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"GoProj/wedy/interactive/grpc"
	"GoProj/wedy/interactive/repository"
	"GoProj/wedy/interactive/repository/cache"
	"GoProj/wedy/interactive/repository/dao"
	"GoProj/wedy/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitIntegrationService() *grpc.InteractiveServiceServer {
	db := InitDB()
	interactiveDao := dao.NewGORMInteractiveDAO(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

var thirdParty = wire.NewSet(InitDB, InitRedis, InitLogger)

var integrationSvcSet = wire.NewSet(cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, dao.NewGORMInteractiveDAO, service.NewInteractiveService)
