// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: seckillActivity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeckillActivity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`                         // 活动ID
	StartTime      int64                  `protobuf:"varint,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`           // 开始时间
	EndTime        int64                  `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`               // 结束时间
	ProductID      int64                  `protobuf:"varint,4,opt,name=ProductID,proto3" json:"ProductID,omitempty"`           // 参与秒杀的商品ID
	Stock          int64                  `protobuf:"varint,5,opt,name=Stock,proto3" json:"Stock,omitempty"`                   // 库存总量
	RemainingStock int64                  `protobuf:"varint,6,opt,name=RemainingStock,proto3" json:"RemainingStock,omitempty"` // 剩余库存
	Price          int64                  `protobuf:"varint,7,opt,name=Price,proto3" json:"Price,omitempty"`                   // 秒杀价格
	Status         int64                  `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`                 // 活动状态（未开始 1/进行中 2/已结束 -1）
	LimitPerUser   int64                  `protobuf:"varint,9,opt,name=LimitPerUser,proto3" json:"LimitPerUser,omitempty"`     // 每人限购数量
	Version        int64                  `protobuf:"varint,10,opt,name=Version,proto3" json:"Version,omitempty"`
	Name           string                 `protobuf:"bytes,11,opt,name=Name,proto3" json:"Name,omitempty"` // 活动名称
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SeckillActivity) Reset() {
	*x = SeckillActivity{}
	mi := &file_seckillActivity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillActivity) ProtoMessage() {}

func (x *SeckillActivity) ProtoReflect() protoreflect.Message {
	mi := &file_seckillActivity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillActivity.ProtoReflect.Descriptor instead.
func (*SeckillActivity) Descriptor() ([]byte, []int) {
	return file_seckillActivity_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillActivity) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SeckillActivity) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SeckillActivity) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SeckillActivity) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *SeckillActivity) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SeckillActivity) GetRemainingStock() int64 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

func (x *SeckillActivity) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeckillActivity) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SeckillActivity) GetLimitPerUser() int64 {
	if x != nil {
		return x.LimitPerUser
	}
	return 0
}

func (x *SeckillActivity) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SeckillActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_seckillActivity_proto protoreflect.FileDescriptor

const file_seckillActivity_proto_rawDesc = "" +
	"\n" +
	"\x15seckillActivity.proto\"\xb5\x02\n" +
	"\x0fSeckillActivity\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1c\n" +
	"\tStartTime\x18\x02 \x01(\x03R\tStartTime\x12\x18\n" +
	"\aEndTime\x18\x03 \x01(\x03R\aEndTime\x12\x1c\n" +
	"\tProductID\x18\x04 \x01(\x03R\tProductID\x12\x14\n" +
	"\x05Stock\x18\x05 \x01(\x03R\x05Stock\x12&\n" +
	"\x0eRemainingStock\x18\x06 \x01(\x03R\x0eRemainingStock\x12\x14\n" +
	"\x05Price\x18\a \x01(\x03R\x05Price\x12\x16\n" +
	"\x06Status\x18\b \x01(\x03R\x06Status\x12\"\n" +
	"\fLimitPerUser\x18\t \x01(\x03R\fLimitPerUser\x12\x18\n" +
	"\aVersion\x18\n" +
	" \x01(\x03R\aVersion\x12\x12\n" +
	"\x04Name\x18\v \x01(\tR\x04NameB\x1aZ\x18wedy/pkg/bigcachex/protob\x06proto3"

var (
	file_seckillActivity_proto_rawDescOnce sync.Once
	file_seckillActivity_proto_rawDescData []byte
)

func file_seckillActivity_proto_rawDescGZIP() []byte {
	file_seckillActivity_proto_rawDescOnce.Do(func() {
		file_seckillActivity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckillActivity_proto_rawDesc), len(file_seckillActivity_proto_rawDesc)))
	})
	return file_seckillActivity_proto_rawDescData
}

var file_seckillActivity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seckillActivity_proto_goTypes = []any{
	(*SeckillActivity)(nil), // 0: SeckillActivity
}
var file_seckillActivity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seckillActivity_proto_init() }
func file_seckillActivity_proto_init() {
	if File_seckillActivity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckillActivity_proto_rawDesc), len(file_seckillActivity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seckillActivity_proto_goTypes,
		DependencyIndexes: file_seckillActivity_proto_depIdxs,
		MessageInfos:      file_seckillActivity_proto_msgTypes,
	}.Build()
	File_seckillActivity_proto = out.File
	file_seckillActivity_proto_goTypes = nil
	file_seckillActivity_proto_depIdxs = nil
}
