redis:
  addr: "127.0.0.1:6379"

db:
  dsn: "root:root@tcp(127.0.0.1:3306)/webook"

kafka:
  addr:
    - "127.0.0.1:9094"

grpc:
  server:
    etcdAddr: "localhost:12379"
    port: 8090
    name: "comment"