// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GoProj/wedy/interactive/events"
	"GoProj/wedy/interactive/grpc"
	"GoProj/wedy/interactive/ioc"
	"GoProj/wedy/interactive/repository"
	"GoProj/wedy/interactive/repository/cache"
	"GoProj/wedy/interactive/repository/dao"
	"GoProj/wedy/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitAPP() *App {
	db := ioc.InitDB()
	interactiveDao := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.NewGrpcxServer(interactiveServiceServer)
	client := ioc.InitSaramaClient()
	loggerV1 := ioc.InitLogger()
	interactiveWatchEventConsumer := events.NewInteractiveWatchEventConsumer(interactiveRepository, client, loggerV1)
	v := ioc.InitConsumer(interactiveWatchEventConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var integrationSvcSet = wire.NewSet(cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, dao.NewGORMInteractiveDAO, service.NewInteractiveService)

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitSaramaClient, ioc.InitRedis, ioc.InitLogger)
